name: CI
on: [push]
jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: asdf
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Run a script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project
    - name: "upload artifact"
      uses: actions/upload-artifact@master
      with:
        artifactName: drop 
        path: .github
